/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const RouterView: typeof import('vue-router')['RouterView']
  const computed: typeof import('vue')['computed']
  const inject: typeof import('vue')['inject']
  const onMounted: typeof import('vue')['onMounted']
  const ref: typeof import('vue')['ref']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useRouter: typeof import('vue-router')['useRouter']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useSwipe: typeof import('@vueuse/core')['useSwipe']
  const watch: typeof import('vue')['watch']
}
